{
	"version": 1682036431,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/chao-sheet0.png",
		"images/sangue_player-sheet0.png",
		"images/sangue_enemy-sheet0.png",
		"images/cenario.png",
		"images/sensor-sheet0.png",
		"images/player-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/select_player-sheet0.png",
		"images/select_player-sheet1.png",
		"images/alma_boss-sheet0.png",
		"images/camera-sheet0.png",
		"images/win_play-sheet0.png",
		"images/win_play-sheet1.png",
		"images/win_play-sheet2.png",
		"images/fade-sheet0.png",
		"images/borda-sheet0.png",
		"images/barra_up_player-sheet0.png",
		"images/barra_up_player-sheet1.png",
		"images/fundo_do_power1-sheet0.png",
		"images/title_power-sheet0.png",
		"images/spanw_play_poderes_medio-sheet0.png",
		"images/spanw_play_poderes_medio-sheet1.png",
		"images/spanw_play_poderes_medio-sheet2.png",
		"images/spanw_play_poderes_alto-sheet0.png",
		"images/spanw_play_poderes_alto-sheet1.png",
		"images/spanw_enemy_poderes_medio-sheet0.png",
		"images/spanw_enemy_poderes_alto-sheet0.png",
		"images/parede-sheet0.png",
		"images/selector_de_personagens-sheet0.png",
		"images/barrar_select-sheet0.png",
		"images/pose_sprites-sheet0.png",
		"images/pose_sprites-sheet1.png",
		"media/fight.ogg",
		"media/final.ogg",
		"media/loser.ogg",
		"media/one.ogg",
		"media/perfect.ogg",
		"media/round.ogg",
		"media/tre 3.ogg",
		"media/two.ogg",
		"media/winner.ogg",
		"media/you.ogg",
		"media/dano especial.ogg",
		"media/soco.ogg",
		"media/soco2.ogg",
		"media/special 1.m4a",
		"media/special 1.ogg",
		"media/mattoglseby - 1.ogg",
		"media/epicarpg.ogg",
		"media/retrolaser1.m4a",
		"media/retrolaser1.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}